version: "3.8"
services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - 4444:4444
  chrome: 
    image: seleniarm/node-chromium:latest
    # volumes:
    #   - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    # environment:
    #   - HUB_HOST=selenium-hub
    #   - HUB_PORT=4444
  firefox:
    image: seleniarm/node-firefox:latest
    # volumes:
    #   - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    # environment:
    #   - HUB_HOST=selenium-hub
    #   - HUB_PORT=4444
  # mvn-tests:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
networks: 
  test-automation-setup: 
    external: true
