version: "3.8"
services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - 4444:4444
    networks:
      - test-automation-setup
  chrome: 
    image: seleniarm/node-chromium:latest
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - test-automation-setup
  firefox:
    image: seleniarm/node-firefox:latest
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - test-automation-setup
  mvn-tests:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sandismalisevs/mvn_tests:latest
    networks:
      - test-automation-setup
    command: mvn clean test -Dbrowser=chrome -DgridURL=selenium-hub:4444
networks: 
  test-automation-setup: 
    external: true
